# Generated by Django 6.0.2 on 2026-04-21 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_date", models.DateTimeField(auto_now_add=True)),
                ("focus_subject", models.CharField(max_length=100)),
                (
                    "plan_content",
                    models.TextField(
                        help_text="HTML formatted study plan from the LLM"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plans",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_date"],
            },
        ),
    ]
